import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Image src="/image.png" alt="matanoj" width="500" height="500" sizes="20vw" className='block m-auto mt-[20vh]' />
      <p className=' abslute text-center text-9xl'>entál</p>
      
    </>
  )
}
